(()=>{'use strict';
const $=id=>document.getElementById(id),fmt=n=>n==null?'—':new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(n),short=n=>new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(n),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const colors=['#66dec2','#b49aff','#ffba76','#78b6ff'],params=new URLSearchParams(location.hash.slice(1));let data,latest,known=new Map(),selected=(params.get('kins')||'YCF2R,1MH1D').split(',').slice(0,4),days=['7','30','365'].includes(params.get('days'))?Number(params.get('days')):7,asc=true;
if(['interactions','creations'].includes(params.get('metric')))$('chartMetric').value=params.get('metric');if(params.get('plot')==='gains')$('chartMode').value='gains';
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),3000);}
function hash(){const q=new URLSearchParams({kins:selected.join(','),days:String(days),metric:$('chartMetric').value,plot:$('chartMode').value});history.replaceState(null,'','#'+q);}
function featuredBadge(id){const f=latest.featured;return f&&Date.now()-Date.parse(f.at)<36*3600000&&f.ids.includes(id)?` <span class="featured-badge" title="Featured by Kindroid · checked ${esc(new Date(f.at).toLocaleString())}">★ Featured</span>`:'';}
function renderTable(){const key=$('sort').value,period=$('period').value,query=$('search').value.toLowerCase().trim(),fixed=['rank','interactions','creations','ratio'].includes(key);$('period').disabled=fixed;$('direction').textContent=asc?'↑ Ascending':'↓ Descending';$('metricHeading').textContent=key==='rank'?'Interactions / creation':$('sort').selectedOptions[0].textContent;
const isRecent=period==='update'||period==='1',window=isRecent?KinMetrics.recentWindow(data,period):null;$('periodNote').hidden=fixed||!isRecent;$('periodNote').textContent=window?`Observed ${new Date(window.startAt).toLocaleString()} → ${new Date(window.endAt).toLocaleString()} (${fmt(window.days*24)} hours). Daily rates use this actual interval.`:'Not enough continuous observations for this period yet.';
let rows=[...known.values()].filter(r=>$('archive').checked||r.current).map(r=>{const stats=fixed?null:KinMetrics.windowStats(data,r.id,period);return{...r,value:key==='rank'?(r.current?r.rank:null):KinMetrics.metric(r,stats,key)};});
rows.sort((a,b)=>a.value==null?(b.value==null?a.name.localeCompare(b.name):1):b.value==null?-1:(asc?a.value-b.value:b.value-a.value)||a.name.localeCompare(b.name));
let position=0;rows=rows.map((r,i)=>{if(r.value!=null&&(i===0||r.value!==rows[i-1].value))position=i+1;return{...r,sortPosition:r.value==null?null:position};}).filter(r=>[r.name,r.creator||'',r.id].some(v=>v.toLowerCase().includes(query)));
$('rows').innerHTML=rows.map(r=>`<tr><td><input type="checkbox" data-id="${esc(r.id)}" aria-label="Compare ${esc(r.name)}" ${selected.includes(r.id)?'checked':''}></td><td class="sort-position">${r.sortPosition==null?'—':'#'+r.sortPosition}</td><td>${r.current?'<span class="rank">#'+r.rank+'</span>':'<span class="muted">Outside 1000</span>'}</td><td><strong>${esc(r.name)}</strong>${featuredBadge(r.id)}<small>${r.creator?esc(r.creator)+' · ':''}${esc(r.id)}${r.current?'':' · Last seen '+new Date(r.seen).toLocaleDateString()}</small></td><td>${fmt(r.interactions)}</td><td>${fmt(r.creations)}</td><td>${fmt(key==='rank'?KinMetrics.metric(r,null,'ratio'):r.value)}${['ipct','cpct'].includes(key)&&r.value!=null?'%':''}</td></tr>`).join('');$('countLabel').textContent=`${rows.length} kins shown · ${selected.length}/4 selected`;}
function renderChart(){hash();document.querySelectorAll('[data-days]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.days)===days));$('selection').innerHTML=selected.map((id,i)=>`<button class="chip" style="--chip:${colors[i]}" data-remove="${esc(id)}">${esc(known.get(id)?.name||id)} ×</button>`).join('');
const end=Date.parse(latest.at),start=end-days*86400000,key=$('chartMetric').value,gains=$('chartMode').value==='gains';let values=[];
const lines=selected.map(id=>{const seq=KinMetrics.series(data,id);return seq.map((p,i)=>{const prev=seq[i-1];let v=p.row?.[key]??null;if(gains)v=KinMetrics.intervalGain(prev,p,key);const point={t:p.t,v,break:i>0&&p.t-prev.t>18*3600000};if(p.t>=start&&v!=null)values.push(v);return point;}).filter(p=>p.t>=start);});
const max=Math.max(1,...values)*1.12,x=t=>72+(t-start)/(end-start)*998,y=v=>245-v/max*215;let svg='';for(let i=0;i<5;i++){const v=max*i/4;svg+=`<line x1="72" y1="${y(v)}" x2="1070" y2="${y(v)}" stroke="#243140"/><text x="61" y="${y(v)+4}" text-anchor="end" fill="#94a4b6" font-size="12">${short(v)}</text>`;}
for(let i=0;i<5;i++){const t=start+(end-start)*i/4;svg+=`<text x="${x(t)}" y="275" text-anchor="${i===4?'end':i===0?'start':'middle'}" fill="#94a4b6" font-size="12">${new Date(t).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</text>`;}
lines.forEach((points,i)=>{let path='',connected=false;for(const p of points){if(p.v==null){connected=false;continue;}path+=`${connected&&!p.break?'L':'M'}${x(p.t)},${y(p.v)} `;connected=true;}svg+=`<path d="${path}" fill="none" stroke="${colors[i]}" stroke-width="2.5"/>`;for(const p of points)if(p.v!=null)svg+=`<circle cx="${x(p.t)}" cy="${y(p.v)}" r="4" fill="${colors[i]}"><title>${esc(known.get(selected[i])?.name)} · ${new Date(p.t).toLocaleString()} · ${fmt(p.v)} ${key}${gains?' gained':''}</title></circle>`;});$('chart').innerHTML=svg;$('chartMessage').textContent=!selected.length?'Select kins below to compare.':!values.length?'No comparable readings yet. Gains appear after the next valid snapshot.':data.snapshots.length===1?'First snapshot saved. The next reading will begin the trend.':'';}
async function load(){try{$('reload').disabled=true;const r=await fetch('history.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error();const fresh=await r.json();if(!fresh.snapshots?.length)throw Error();data=fresh;latest=data.snapshots.at(-1);known=new Map();for(const s of data.snapshots)for(const row of s.rows)known.set(row.id,{...row,seen:s.at,current:false});for(const r of latest.rows)known.get(r.id).current=true;selected=selected.filter(id=>known.has(id));$('kinCount').textContent=latest.rows.length;$('totalI').textContent=short(latest.rows.reduce((a,r)=>a+r.interactions,0));$('interactionCoverage').textContent=latest.rows.some(r=>r.interactions==null)?'Available totals · '+latest.rows.filter(r=>r.interactions==null).length+' hidden by Kindroid':'Across the latest discovery set';$('totalC').textContent=short(latest.rows.reduce((a,r)=>a+r.creations,0));$('readingCount').textContent=data.snapshots.length;$('historySince').textContent='Since '+new Date(data.snapshots[0].at).toLocaleDateString();const stale=Date.now()-Date.parse(latest.at)>18*3600000;$('freshness').textContent=`${data.automated?'Automatic collection':'Manual baseline · automation pending'} · Last reading ${new Date(latest.at).toLocaleString()}${stale?' · Update overdue':''}`;$('statusDot').style.background=stale?'#ffba76':'#66dec2';renderTable();renderChart();}catch{$('freshness').textContent='Could not load data. Try refreshing shortly.';}finally{$('reload').disabled=false;}}
$('rows').addEventListener('change',e=>{const id=e.target.dataset.id;if(!id)return;if(e.target.checked){if(selected.length===4){e.target.checked=false;toast('Select up to four kins. Remove one to add another.');return;}selected.push(id);}else selected=selected.filter(v=>v!==id);renderTable();renderChart();});$('selection').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(b){selected=selected.filter(v=>v!==b.dataset.remove);renderTable();renderChart();}});
for(const id of ['search','archive','period'])$(id).addEventListener(id==='search'?'input':'change',renderTable);$('sort').addEventListener('change',()=>{asc=$('sort').value==='rank';renderTable();});$('direction').onclick=()=>{asc=!asc;renderTable();};for(const id of ['chartMetric','chartMode'])$(id).onchange=renderChart;document.querySelectorAll('[data-days]').forEach(b=>b.onclick=()=>{days=Number(b.dataset.days);renderChart();});$('reload').onclick=load;
$('share').onclick=async()=>{hash();try{await navigator.clipboard.writeText(location.href);toast('Comparison link copied.');}catch{toast('Copy the page address to share this comparison.');}};$('csv').onclick=()=>{if(!data)return;const cell=v=>'"'+String(v??'').replaceAll('"','""')+'"';const rows=[['observed_at','share_code','name','discovery_rank','interactions','creations'],...data.snapshots.flatMap(s=>s.rows.map(r=>[s.at,r.id,/^[=+@-]/.test(r.name)?"'"+r.name:r.name,r.rank,r.interactions,r.creations]))];const url=URL.createObjectURL(new Blob([rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='kin-observatory-history.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};load();
})();
