(()=>{'use strict';const $=id=>document.getElementById(id),DAY=86400000,GAP=18*3600000;
const kins=[['YCF2R','Sense Mod World','#b8e6c0'],['RKH4I','Pam','#c4a1db'],['1MH1D','NPC','#7faecc'],['TWHFG','Shadow','#e0b880'],['78ZO7','Natalie & Darius','#d7939e'],['4XDPE','Missy','#a6b9e5'],['6YMWL','Derek Hawk','#ef9675'],['P74I0','Lyla','#70c9c2']];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=n=>n==null?'—':new Intl.NumberFormat('en-US',{maximumFractionDigits:1}).format(n),signed=n=>n==null?'—':(n>0?'+':'')+num(n),compact=n=>new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(n);
const params=new URLSearchParams(location.hash.slice(1));let range=['7','30','365','all'].includes(params.get('range'))?params.get('range'):'7',visible=new Set(params.has('kins')?params.get('kins').split(','):kins.map(k=>k[0]));visible.add('YCF2R');let data,events=[],eventError='',latest;
if(['interactions','creations'].includes(params.get('measure')))$('measure').value=params.get('measure');if(['gains','total','pace'].includes(params.get('view')))$('view').value=params.get('view');$('markers').checked=params.get('markers')!=='0';
function delta(a,b,field){return a?.row&&b?.row&&b.t>a.t&&b.t-a.t<=GAP&&b.row[field]>=a.row[field]?b.row[field]-a.row[field]:null;}
function stats(id,period=range){return KinMetrics.windowStats(data,id,period);}
function draw(){const end=Date.parse(latest.at),start=range==='all'?Date.parse(data.snapshots[0].at):end-Number(range)*DAY,field=$('measure').value,mode=$('view').value;history.replaceState(null,'','#'+new URLSearchParams({kins:kins.filter(k=>visible.has(k[0])).map(k=>k[0]).join(','),range,measure:field,view:mode,markers:$('markers').checked?'1':'0'}));
document.querySelectorAll('[data-range]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.range===range));$('toggles').innerHTML=kins.map(([id,name,color],i)=>`<button class="toggle ${i===0?'primary':''}" data-id="${id}" style="--color:${color}" aria-pressed="${visible.has(id)}" ${i===0?'disabled':''}><i></i>${esc(name)}</button>`).join('');
let values=[],hasRebasedGap=false;const plots=kins.filter(k=>visible.has(k[0])).map(k=>{const seq=KinMetrics.series(data,k[0]);let base=null,broken=false;const points=seq.map((p,i)=>{if(p.t<start)return null;const prev=seq[i-1];let v=p.row?.[field]??null;if(mode==='pace'){const d=delta(prev,p,field);v=d==null?null:d/((p.t-prev.t)/DAY);}else if(mode==='gains'){if(base===null&&v!=null)base=v;else if(base!==null&&(!p.row||!prev?.row||p.t-prev.t>GAP||p.row[field]<prev.row[field]))broken=true;v=broken||v==null?null:v-base;if(broken)hasRebasedGap=true;}if(v!=null)values.push(v);return{t:p.t,v,break:!!prev&&p.t-prev.t>GAP};}).filter(Boolean);return{k,points};});
const max=Math.max(1,...values)*1.14,x=t=>76+(t-start)/Math.max(1,end-start)*1014,y=v=>294-v/max*250;let svg='';for(let i=0;i<5;i++){const v=max*i/4;svg+=`<line x1="76" y1="${y(v)}" x2="1090" y2="${y(v)}" stroke="#293b40"/><text x="65" y="${y(v)+4}" text-anchor="end" fill="#99adaf" font-size="11">${compact(v)}</text>`;}for(let i=0;i<5;i++){const t=start+(end-start)*i/4;svg+=`<text x="${x(t)}" y="325" text-anchor="${i===0?'start':i===4?'end':'middle'}" fill="#99adaf" font-size="11">${new Date(t).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</text>`;}
const shownEvents=$('markers').checked?events.filter(e=>e.t>=start&&e.t<=end):[];shownEvents.forEach((e,i)=>{svg+=`<g><title>${esc(e.label)} · ${new Date(e.t).toLocaleString()}${e.notes?' · '+esc(e.notes):''}</title><line x1="${x(e.t)}" y1="33" x2="${x(e.t)}" y2="294" stroke="#d8c399" stroke-dasharray="4 5" opacity=".7"/><circle cx="${x(e.t)}" cy="22" r="10" fill="#d8c399"/><text x="${x(e.t)}" y="26" fill="#142021" text-anchor="middle" font-size="10">${i+1}</text></g>`;});
plots.reverse().forEach(({k,points})=>{let d='',connected=false;for(const p of points){if(p.v==null){connected=false;continue;}d+=`${connected&&!p.break?'L':'M'}${x(p.t)},${y(p.v)} `;connected=true;}svg+=`<path d="${d}" fill="none" stroke="${k[2]}" stroke-width="${k[0]==='YCF2R'?3.3:1.8}" opacity="${k[0]==='YCF2R'?1:.75}"/>`;for(const p of points)if(p.v!=null)svg+=`<circle cx="${x(p.t)}" cy="${y(p.v)}" r="${k[0]==='YCF2R'?4:3}" fill="${k[2]}"><title>${esc(k[1])} · ${new Date(p.t).toLocaleString()} · ${num(p.v)} ${field}${mode==='pace'?' / day':mode==='gains'?' gained':''}</title></circle>`;});$('chart').innerHTML=svg;
$('chartNote').textContent=!values.length?'No comparable readings yet. Another valid observation is needed.':mode==='gains'?'Each line starts at its first available reading within this view. '+(hasRebasedGap?'Growth lines stop at missing observations or counter resets. ':'')+'Hover or tap a point for its value.':mode==='pace'?'Daily pace = change between consecutive observations ÷ actual elapsed days. Short intervals can look volatile; gaps over 18 hours are excluded.':'Lifetime counters at each observation. Missing readings break the line.';
$('eventLegend').innerHTML=shownEvents.map((e,i)=>`<a href="#event-${e.index}">${i+1} · ${esc(e.label)}</a>`).join('');renderTables();}
function renderTables(){const smw=latest.rows.find(r=>r.id==='YCF2R'),s=stats('YCF2R');$('gaps').innerHTML=kins.slice(1).filter(k=>visible.has(k[0])).map(([id,name])=>{const row=latest.rows.find(r=>r.id===id),other=stats(id),gap=row&&smw?smw.interactions-row.interactions:null,change=s&&other?s.interactions-other.interactions:null;return`<tr><td>${esc(name)}</td><td class="${gap>0?'positive':gap<0?'negative':''}">${signed(gap)}</td><td class="${change>0?'positive':change<0?'negative':''}">${signed(change)}</td></tr>`;}).join('')||'<tr><td colspan="3">Turn on a competitor above to compare gaps.</td></tr>';
$('updates').innerHTML=kins.filter(k=>visible.has(k[0])).map(([id,name])=>{const seq=KinMetrics.series(data,id),last=seq.at(-1),prev=seq.at(-2);return`<tr class="${id==='YCF2R'?'primary':''}"><td>${esc(name)}</td><td>${signed(delta(prev,last,'interactions'))}</td><td>${signed(delta(prev,last,'creations'))}</td><td>${num(last.row?.creations?last.row.interactions/last.row.creations:null)}</td></tr>`;}).join('');const prev=data.snapshots.at(-2);$('latestNote').textContent=prev?`${new Date(prev.at).toLocaleString()} → ${new Date(latest.at).toLocaleString()} · actual observation interval`:'First observation saved. Changes appear after the next reading.';}
function summary(){const seq=KinMetrics.series(data,'YCF2R'),last=seq.at(-1),row=last.row,prev=seq.at(-2);$('interactions').textContent=num(row?.interactions);$('creations').textContent=num(row?.creations);$('rank').textContent=row?'#'+row.rank:'Outside 1000';$('ratio').textContent=row?'Interactions / creation: '+num(row.creations?row.interactions/row.creations:null):'History retained; no current observation';$('interactionChange').textContent=signed(delta(prev,last,'interactions'))+' since previous reading';$('creationChange').textContent=signed(delta(prev,last,'creations'))+' since previous reading';const recent=stats('YCF2R',7);$('daily').textContent=num(recent?.perDay);$('thisWeek').textContent=num(recent?.perDay);const target=last.t-7*DAY,old=data.snapshots.filter(s=>Date.parse(s.at)<=target),prior=old.length&&target-Date.parse(old.at(-1).at)<=GAP?KinMetrics.windowStats({snapshots:old},'YCF2R',7):null;$('lastWeek').textContent=num(prior?.perDay);const pct=recent&&prior?.perDay>0?(recent.perDay/prior.perDay-1)*100:null;$('momentum').textContent=pct==null?'Building history':signed(pct)+'%';$('momentum').style.fontSize=pct==null?'32px':'50px';$('momentumNote').textContent=pct==null?'Two complete weeks will reveal whether the pace is changing.':pct>0?'A faster interaction rate than the previous seven days.':pct<0?'A slower interaction rate than the previous seven days.':'The same interaction rate as the previous seven days.';}
function renderEvents(){const warnings=eventError?`<p role="alert" class="negative">${esc(eventError)}</p>`:'';$('events').innerHTML=warnings+(events.length?events.map(e=>`<article class="event" id="event-${e.index}"><time datetime="${esc(e.at)}">${new Date(e.t).toLocaleString()}</time><div><h3>${esc(e.label)} <span class="tag">${esc(e.type||'other')}</span></h3>${e.notes?'<p>'+esc(e.notes)+'</p>':''}</div></article>`).join(''):eventError?'':'<div class="empty">No events recorded yet. Add your first advertising, model, or update milestone through Manage events.</div>');}
async function load(){ $('refresh').disabled=true;try{const r=await fetch('../history.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error();const next=await r.json();if(!next.snapshots?.length)throw Error();data=next;latest=data.snapshots.at(-1);$('freshness').textContent=`${data.automated?'Cloud collection':'Manual baseline'} · ${new Date(latest.at).toLocaleString()} · ${data.snapshots.length} observations${Date.now()-Date.parse(latest.at)>GAP?' · Update overdue':''}`;eventError='';events=[];try{const er=await fetch('events.json?t='+Date.now(),{cache:'no-store'});if(!er.ok)throw Error();const raw=await er.json();if(!Array.isArray(raw))throw Error();raw.forEach((e,index)=>{if(!e||typeof e.at!=='string'||!/(Z|[+-]\d{2}:\d{2})$/.test(e.at)||!Number.isFinite(Date.parse(e.at))||typeof e.label!=='string'||!e.label.trim()){eventError='Some events are invalid and were omitted. Check the events file.';return;}events.push({at:e.at,t:Date.parse(e.at),label:e.label,notes:typeof e.notes==='string'?e.notes:'',type:typeof e.type==='string'?e.type:'other',index});});events.sort((a,b)=>a.t-b.t);}catch{eventError='Events could not be loaded. Check events.json and refresh.';}summary();renderEvents();draw();}catch{$('freshness').textContent='Could not load observations. Please refresh shortly.';}finally{$('refresh').disabled=false;}}
$('toggles').onclick=e=>{const b=e.target.closest('[data-id]');if(!b||b.dataset.id==='YCF2R')return;visible.has(b.dataset.id)?visible.delete(b.dataset.id):visible.add(b.dataset.id);draw();};$('showAll').onclick=()=>{visible=new Set(kins.map(k=>k[0]));draw();};$('hideAll').onclick=()=>{visible=new Set(['YCF2R']);draw();};document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{range=b.dataset.range;draw();});for(const id of ['measure','view','markers'])$(id).onchange=draw;$('refresh').onclick=load;load();})();
